### PR TITLE
Nix test

### PR DESCRIPTION
**Pull request by allgreed**
Make the CLI sensibly buildable with nix

### CODE REVIEW

**Review by vduseev — APPROVED** [review]
Looks good

**Comment by wbachnik** [comment]
I don't believe we should downgrade to vulnerable dependency versions just for the sake of building with Nix.

**Comment by allgreed** [comment]
@wbachnik well, I definitely agree that the final state of being able to build with nix, but having downgraded crypto libraries is unacceptable. 

We have two options: 
- fall-back (decline the PR, until nix support can be added without downgrading)
- fall-forward (accept the PR and then make a priority to make it work with proper library versions)

I'd say fall-forward is acceptable given the maturity and existing user base of the tool, but I believe that you should have the final call (and either merge the PR or review with "request changes").

**Comment by allgreed** [comment]
We kindof got around this by using the binary ;d

**Pull request closed without merging**
