### PR TITLE
certificates-generation-enhancements

### PR DESCRIPTION
**Pull request by Mendrzec**
* overwriting root certificate with --force option
* certificate fields can be customized with  `--ca-subject` and `--dev-subject` parameters (format same as in `openssl req -subj`)
* devcert issuer is loaded from root certificate
* devcert's subject can't be the same as it issuer (@wbachnik I discarded solution that compares only the CN component since it seems to be optional, instead whole DN is compared)
* certificates files extensions changed to `.pem`
* added `gencerts` command that simplifies useg

### CODE REVIEW

**Comment by wbachnik** [comment]
I think we really should have some tests for the added functionality :-)

**Review by wbachnik — CHANGES_REQUESTED** [review]
Please add tests covering new features.

**Review by vduseev — DISMISSED** [review]

**Comment by Mendrzec** [comment]
I will include additional `gencerts` command and rename the certificates extension into `.pem` in this PR

**Review by wbachnik — APPROVED** [review]
LGTM

**Pull request merged**
